import { Schema, model } from "mongoose";
import Counter from "./Counter.js";

const generalInfoSchema = new Schema({
  lastName: { type: String, required: true },
  firstName: { type: String, required: true },
  middleName: String,
  prefix: { type: String, enum: ["Mr.", "Ms."] },
  suffix: String,
  employeeType: {
    type: String,
    enum: ["Probationary", "Regular", "Casual", "On-Call", "Contractual"],
  },
  branch: { type: String, required: true },
  department: { type: String, required: true },
  jobTitle: { type: String, required: true },
  employmentDate: { type: Date, required: true },
  regularizationDate: { type: Date, required: true },
  resignationDate: Date,
  resignationReason: String,
});

const personalInfoSchema = new Schema({
  birthdate: Date,
  birthplace: String,
  presentAddress: String,
  permanentAddress: String,
  zipCode: Number,
  contactNo: String,
  father: {
    name: String,
    occupation: String,
    contactNo: String,
  },
  mother: {
    name: String,
    occupation: String,
    contactNo: String,
  },
});

const governmentIdsSchema = new Schema({
  pagIbig: { type: String, required: true },
  philHealth: { type: String, required: true },
  sss: { type: String, required: true },
  tin: { type: String, required: true },
});

const dependentSchema = new Schema(
  {
    name: { type: String, default: "" },
    birthdate: { type: Date, default: null },
  },
  { _id: false } // optional if you don't want autogenerated _id for each dependent
);

const educHistorySchema = new Schema(
  {
    institutionName: String,
    yrStarted: Number,
    yrGraduated: Number,
    educationType: { type: String, enum: ["Primary", "Secondary", "Tertiary"] },
  },
  { _id: false }
);

const workHistorySchema = new Schema(
  {
    companyName: String,
    address: String,
    monthEmployed: String,
    yearEmployed: Number,
    monthResigned: String,
    yearResigned: Number,
    responsibilites: String,
  },
  { _id: false }
);

const employeeSchema = new Schema(
  {
    empID: { type: String, default: "", immutable: true, unique: true },
    bioID: { type: Number, default: null, unique: true },
    genInfo: { type: generalInfoSchema },
    personalInfo: { type: personalInfoSchema },
    governmentIds: { type: governmentIdsSchema },
    dependents: { type: [dependentSchema], default: [] },
    educHistory: { type: [educHistorySchema], default: [] },
    workHistory: { type: [workHistorySchema], default: [] },
  },
  { toJSON: { virtuals: true } }
);

employeeSchema.virtual("fullName").get(function () {
  return `${
    this.genInfo.lastName
  }, ${this.genInfo.firstName} ${Boolean(this.genInfo.middleName) ? this.genInfo.middleName.substring(0, 1).concat(".") : ""}`;
});

employeeSchema.pre("save", async function (next) {
  if (!this.isNew) return next(); // Only run on new employees

  try {
    const branch = this.genInfo.branch;

    // Safety: ensure branch exists
    if (!branch || branch.length < 2) {
      throw new Error("Branch name must be at least 2 characters.");
    }

    // Get first 2 letters and uppercase them
    const branchCode = branch.substring(0, 2).toUpperCase();

    // Increment counter for this branch code
    const counter = await Counter.findOneAndUpdate(
      { branchCode },
      { $inc: { seq: 1 } },
      { new: true, upsert: true }
    );

    // Format ID like: "BR-0001"
    const formattedId = `${branchCode}-${String(counter.seq).padStart(4, "0")}`;

    this.empID = formattedId;

    next();
  } catch (err) {
    next(err);
  }
});

const Employee = model("Employee", employeeSchema);
export default Employee;
